
Datasets:
  datasets_dir: "/home/oliver/Documents/github/Datasets"


Dataloader:
  batch_size: 100
  img_per_place: 4
  min_img_per_place: 4
  cities:
    - London
    - Boston
    - Melbourne
  image_size:
    - 224
    - 224
  num_workers: 8
  shuffle_all: True
  random_sample_from_each_place: True
  show_data_stats: True
  val_set_names:
    - pitts30k_val

Training:
  accelerator: 'gpu'
  devices:
    - 0
  precision: 16
  max_epochs: 30
  fast_dev_run: False

  lr: 0.0002
  optimizer: 'adam'
  weight_decay: 0
  momentum: 0.9
  warmup_steps: 600
  milestones:
    - 5
    - 10
    - 15
    - 25
  lr_mult: 0.3
  loss_name: 'MultiSimilarityLoss'
  miner_name: 'MultiSimilarityMiner'
  miner_margin: 0.1
  faiss_gpu: False

  monitor: 'pitts30k_val/R1'


Model:
  backbone_arch: 'resnet18'
  pretrained: True
  layers_to_freeze: 2
  layers_to_crop:
    -
  agg_arch: 'ConvAP'
  agg_config:
    convap_in_channels: 512
    convap_out_channels: 512
    convap_s1: 2
    convap_s2: 2
    cosplace_in_dim: 2048
    cosplace_out_dim: 1024
    gem_p: 3



Qauntize:
  qlinear: LinearW8A16
  qconv: Conv2dW8A16