
Datasets:
  datasets_dir: "/mnt/datasets_drive/vpr_datasets"


Dataloader:
  batch_size: 40 #100 if possible
  img_per_place: 4
  min_img_per_place: 4
  cities:
   # - Bangkok
   # - BuenosAires
   # - LosAngeles
   # - MexicoCity
   # - OSL # refers to Oslo
   # - Rome
   # - Barcelona
   # - Chicago
   # - Madrid
   # - Miami
   # - Phoenix
   # - TRT # refers to Toronto
    - Boston
   # - Lisbon
   # - Medellin
   # - Minneapolis
   # - PRG # refers to Prague
   # - WashingtonDC
   # - Brussels
    - London
    - Melbourne
   # - Osaka
   # - PRS # refers t
  image_size:
    - 224
    - 224
  num_workers: 16
  shuffle_all: True
  random_sample_from_each_place: True
  show_data_stats: True
  val_set_names:
    - pitts30k_val

Training:
  accelerator: 'gpu'
  devices:
    - 0
  precision: 16
  max_epochs: 30 # 30 for pretraining
  fast_dev_run: False

  lr: 0.0002 # 0.0002 for pre-training
  optimizer: 'adam' #adam
  weight_decay: 0
  momentum: 0.9
  warmup_steps: 100 # 600
  milestones:
    - 5
    - 10
    - 15
    - 25
  lr_mult: 0.3
  loss_name: 'MultiSimilarityLoss'
  miner_name: 'MultiSimilarityMiner'
  miner_margin: 0.1
  faiss_gpu: False
  search_precision: 'binary'


  lambda_lat: 1.
  lambda_front: 1.
  iterations_per_epoch: 5000
  M: 15 
  N: 3
  s: 300
  m: 0.4
  n: 2
  focal_dist: 25
  min_images_per_class: 5
  visualize_calsses: 0

  monitor: 'pitts30k_val/R1'


Model:
  load_checkpoint: ""
  backbone_arch: 'resnet18'
  pretrained: True
  layers_to_freeze: 2
  layers_to_crop:
    -
  agg_arch: 'ConvAP'
  backbone_config: 
    resnet18: 
      model_name: 'resnet18'
      pretrained: True
      layers_to_freeze: 2
      layers_to_crop: 
        -
    resnet50: 
      model_name: 'resnet50'
      pretrained: True
      layers_to_freeze: 2
      layers_to_crop: 
        -
    efficientnet: 
      model_name: 'efficientnet_b0'
      pretrained: True
      layers_to_freeze: 4

    dinov2: 
      model_name: 'dinov2_vits14'
      num_trainable_blocks: 4
      norm_layer: True
      return_token: True

    swin: 
      model_name: 'swinv2_base_window12to16_192to256_22kft1k'
      pretrained: True 
      layers_to_freeze: 2

    vit: 
      model_name: 'vit224'
      pretrained: True 
      layers_to_freeze: 4
      layers_to_truncate: 10
    


  agg_config:
    convap: 
      in_channels: 512
      out_channels: 512
      s1: 2
      s2: 2
    gem: 
      p: 3
    cosplace: 
      in_dim: 1024
      out_dim: 1024
    mixvpr: 
      in_channels: 512 
      out_channels: 4 
      in_h: 10
      in_w: 4
      mix_depth: 4
    salad: 
      num_channels: 384
      num_clusters: 64
      cluster_dim: 128
      token_dim: 256
    fully_connected: 
      in_channels: 512
      spatial_dims: 
        - 7
        - 7 
      out_dim: 512
    cls: 





    convap_in_channels: 512
    convap_out_channels: 512
    convap_s1: 2
    convap_s2: 2
    cosplace_in_dim: 2048
    cosplace_out_dim: 1024
    gem_p: 3


Quantize:
  qlinear: LinearW4A16
  qconv: Conv2dW4A8