
Datasets:
  datasets_dir: "/mnt/datasets_drive/vpr_datasets"

  
  
  


Training:
  training_method: gsvcities
  monitor: 'pitts30k_val/R1'
  accelerator: 'gpu'
  precision: 16
  batch_size: 64
  max_epochs: 30 # 30 for pretraining
  search_precision: 'float32'
  fast_dev_run: False
  val_set_names:
    - pitts30k_val
  num_workers: 16
  image_size:
    - 224
    - 224
  shuffle_all: True

  GSVCities: 
    optimizer: 'adam' #adam
    weight_decay: 0
    momentum: 0.9
    warmup_steps: 100 # 600
    milestones:
      - 5
      - 10
      - 15
      - 25
    lr_mult: 0.3
    loss_name: 'MultiSimilarityLoss'
    miner_name: 'MultiSimilarityMiner'
    miner_margin: 0.1
    faiss_gpu: False
    random_sample_from_each_place: True
    show_data_stats: True
    img_per_place: 4
    min_img_per_place: 4
    cities:
    # - Bangkok
    # - BuenosAires
    # - LosAngeles
    # - MexicoCity
    # - OSL # refers to Oslo
    # - Rome
    # - Barcelona
    # - Chicago
    # - Madrid
    # - Miami
    # - Phoenix
    # - TRT # refers to Toronto
      - Boston
    # - Lisbon
    # - Medellin
    # - Minneapolis
    # - PRG # refers to Prague
    # - WashingtonDC
    # - Brussels
      - London
      - Melbourne
    # - Osaka
    # - PRS # refers t
    

  EigenPlaces: 
    dataset_size: small
    lr: 0.00001
    classifier_lr: 0.01
    lambda_lat: 1.
    lambda_front: 1.
    iterations_per_epoch: 500
    M: 15 
    N: 3
    s: 100
    m: 0.4
    focal_dist: 10
    min_images_per_class: 5
    visualize_classes: 0
    brightness: 0.7
    contrast: 0.7
    saturation: 0.7 
    hue: 0.5
    random_resized_crop: 0.5


Model:
  load_checkpoint: ""
  backbone_arch: 'resnet18'
  agg_arch: 'GeM'

  backbone_config: 
    resnet18: 
      model_name: 'resnet18'
      pretrained: True
      layers_to_freeze: 2
      layers_to_crop: 
        -
    resnet50: 
      model_name: 'resnet50'
      pretrained: True
      layers_to_freeze: 2
      layers_to_crop: 
        -
    efficientnet: 
      model_name: 'efficientnet_b0'
      pretrained: True
      layers_to_freeze: 4

    dinov2: 
      model_name: 'dinov2_vits14'
      num_trainable_blocks: 4
      norm_layer: True
      return_token: True

    swin: 
      model_name: 'swinv2_base_window12to16_192to256_22kft1k'
      pretrained: True 
      layers_to_freeze: 2

    vit: 
      model_name: 'vit224'
      pretrained: True 
      layers_to_freeze: 4
      layers_to_truncate: 10
    


  agg_config:
    convap: 
      in_channels: 512
      out_channels: 128
      s1: 2
      s2: 2
    gem: 
      p: 3
    cosplace: 
      in_dim: 1024
      out_dim: 1024
    mixvpr: 
      in_channels: 512 
      out_channels: 4 
      in_h: 10
      in_w: 4
      mix_depth: 4
    salad: 
      num_channels: 384
      num_clusters: 64
      cluster_dim: 128
      token_dim: 256
    fully_connected: 
      in_channels: 512
      spatial_dims: 
        - 7
        - 7 
      out_dim: 512
    cls: 



Quantize:
  qlinear: LinearW4A16
  qconv: Conv2dW4A8