
Datasets:
  #datasets_dir: "/mnt/datasets_drive/vpr_datasets"
  #datasets_dir: "/Users/olivergrainge/Documents/github/Datasets"
  datasets_dir: "/scratch/oeg1n18/datasets/vpr"

  
Training:
  load_checkpoint: ''
  backbone_arch: 'vit_small'
  agg_arch: 'cls'
  out_dim: 1024
  training_method: gsvcities
  monitor: 'pitts30k_val/R1'
  accelerator: 'gpu'
  precision: bf16-mixed
  batch_size: 100 #416 for pretraining
  max_epochs: 10
  search_precision: 'float32'
  fast_dev_run: False
  freeze_n_blocks: 8
  val_set_names:
    - pitts30k_val
    #- sped
  num_workers: 12
  image_size: 224 224


  GSVCities: 
    shuffle_all: True
    optimizer: 'adamw' #adam
    lr: 0.0002
    weight_decay: 0.0
    momentum: 0.9
    warmup_steps: 100 # 600
    milestones:
      - 30
      - 40
      - 50
      - 65
    lr_mult: 0.3
    loss_name: 'MultiSimilarityLoss'
    miner_name: 'MultiSimilarityMiner'
    miner_margin: 0.1
    faiss_gpu: False
    random_sample_from_each_place: True
    show_data_stats: True
    img_per_place: 4
    min_img_per_place: 4
    cities:
     #- Bangkok
     #- BuenosAires
     #- LosAngeles
     #- MexicoCity
     #- OSL # refers to Oslo
     #- Rome
     #- Barcelona
     #- Chicago
     #- Madrid
     #- Miami
     #- Phoenix
     #- TRT # refers to Toronto
     - Boston
     #- Lisbon
     #- Medellin
     #- Minneapolis
     #- PRG # refers to Prague
     #- WashingtonDC
     #- Brussels
     - London
     - Melbourne
     #- Osaka
     #- PRS # refers t
    

  EigenPlaces: 
    dataset_size: small
    weight_decay: 0.001
    lr: 0.0001 # 0.00001 for large dataset
    classifiers_lr: 0.01
    lambda_lat: 1.
    lambda_front: 1.
    iterations_per_epoch: 2000
    M: 15 
    N: 3
    s: 100
    m: 0.4
    focal_dist: 10
    min_images_per_class: 5
    visualize_classes: 0
    brightness: 0.7
    contrast: 0.7
    saturation: 0.7 
    hue: 0.5
    random_resized_crop: 0.5

  Distill: 
    lr: 0.001
    teacher_preset: 'EigenPlaces'
    data_directory: '/scratch/oeg1n18/datasets/vpr/gsvcities/Images/London'
    