
Datasets:
  #datasets_dir: "/mnt/datasets_drive/vpr_datasets"
  datasets_dir: "/Users/olivergrainge/Documents/github/Datasets"
  #datasets_dir: "/scratch/oeg1n18/datasets/vpr"

  
Training:
  pbar: True
  load_checkpoint: ''
  backbone_arch: 'vit_small'
  agg_arch: 'cls'
  out_dim: 512
  training_method: gsvcities
  precision: bf16-mixed
  batch_size: 256 #416 for pretraining
  max_epochs: 1000
  search_precision: 'float32'
  num_workers: 12
  image_size: [224, 224]
  lr: 0.0001


  TeTRA: 
    shuffle_all: True
    optimizer: 'adamw' #adam
    weight_decay: 0.0
    momentum: 0.9
    warmup_steps: 100 # 600
    milestones:
      - 30
      - 40
      - 50
      - 65
    lr_mult: 0.3
    loss_name: 'MultiSimilarityLoss'
    miner_name: 'MultiSimilarityMiner'
    miner_margin: 0.1
    faiss_gpu: False
    random_sample_from_each_place: True
    show_data_stats: True
    img_per_place: 4
    min_img_per_place: 4
    cities:
     #- Bangkok
     #- BuenosAires
     #- LosAngeles
     #- MexicoCity
     #- OSL # refers to Oslo
     #- Rome
     #- Barcelona
     #- Chicago
     #- Madrid
     #- Miami
     #- Phoenix
     #- TRT # refers to Toronto
     - Boston
     #- Lisbon
     #- Medellin
     #- Minneapolis
     #- PRG # refers to Prague
     #- WashingtonDC
     #- Brussels
     - London
     - Melbourne
     #- Osaka
     #- PRS # refers t


  Distill: 
    teacher_preset: 'DinoSalad'
    use_attention: True
    weight_decay_init: 0.05
    mse_loss_mult: 1000
    weight_decay_schedule: 'staged_linear_decreasing'
    augment_level: 'LightAugment'
    #data_directory: '/scratch/oeg1n18/datasets/vpr/gsvcities/Images/London'
    #data_directory: '/scratch/oeg1n18/datasets/vpr/sf_xl/small/train'
    #data_directory: '/scratch/oeg1n18/datasets/vpr/sf_xl/raw/train/panoramas'
    #data_directory: '/home/oliver/datasets_drive/vpr_datasets/Pittsburgh-Query/query'
    data_directory: '/Users/olivergrainge/Documents/github/Datasets/Pittsburgh-Query/query'